pool:
  vmImage:'windows-2019'

steps:
- task: DotNetCoreCLI@2
  displayName: "Restore Packages"
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: "Build Solution"
  inputs:
    command: 'build'
    configuration: 'Release'

